// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import '../../domain/entities/cart_item_entity.dart';
import '../../domain/entities/customer_entity.dart';
import '../../domain/entities/product_entity.dart';
import '../../domain/entities/shop_order_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 4850974843288692582),
    name: 'CartItem',
    lastPropertyId: const obx_int.IdUid(7, 1531888078167569134),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7712849893499057141),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8237497419310626862),
        name: 'productId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7579733161200587961),
        name: 'productName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3180718053263272734),
        name: 'productPrice',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 676127715149326256),
        name: 'productStock',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 526490462677354201),
        name: 'productQty',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 1531888078167569134),
        name: 'shopOrderId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(1, 668324892238423576),
        relationTarget: 'ShopOrder',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 2228730238278008597),
    name: 'Customer',
    lastPropertyId: const obx_int.IdUid(2, 3553469999894954502),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6674191979267619510),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3553469999894954502),
        name: 'email',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 974434976712259507),
    name: 'Product',
    lastPropertyId: const obx_int.IdUid(4, 5318278884433399804),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7463350100456135083),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8448101543605047856),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8303237717742247077),
        name: 'price',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5318278884433399804),
        name: 'stock',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 1464930533826628168),
    name: 'ShopOrder',
    lastPropertyId: const obx_int.IdUid(3, 5752908084191189607),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 9009440605062702307),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5851712318916019894),
        name: 'date',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5752908084191189607),
        name: 'total',
        type: 8,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'items',
        srcEntity: 'CartItem',
        srcField: 'shopOrder',
      ),
    ],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(4, 1464930533826628168),
    lastIndexId: const obx_int.IdUid(1, 668324892238423576),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    CartItem: obx_int.EntityDefinition<CartItem>(
      model: _entities[0],
      toOneRelations: (CartItem object) => [object.shopOrder],
      toManyRelations: (CartItem object) => {},
      getId: (CartItem object) => object.id,
      setId: (CartItem object, int id) {
        object.id = id;
      },
      objectToFB: (CartItem object, fb.Builder fbb) {
        final productNameOffset = fbb.writeString(object.productName);
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.productId);
        fbb.addOffset(2, productNameOffset);
        fbb.addFloat64(3, object.productPrice);
        fbb.addInt64(4, object.productStock);
        fbb.addInt64(5, object.productQty);
        fbb.addInt64(6, object.shopOrder.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final productIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final productNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final productPriceParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final productStockParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final productQtyParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final object = CartItem(
          id: idParam,
          productId: productIdParam,
          productName: productNameParam,
          productPrice: productPriceParam,
          productStock: productStockParam,
          productQty: productQtyParam,
        );
        object.shopOrder.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        object.shopOrder.attach(store);
        return object;
      },
    ),
    Customer: obx_int.EntityDefinition<Customer>(
      model: _entities[1],
      toOneRelations: (Customer object) => [],
      toManyRelations: (Customer object) => {},
      getId: (Customer object) => object.id,
      setId: (Customer object, int id) {
        object.id = id;
      },
      objectToFB: (Customer object, fb.Builder fbb) {
        final emailOffset = fbb.writeString(object.email);
        fbb.startTable(3);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, emailOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final emailParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final object = Customer(id: idParam, email: emailParam);

        return object;
      },
    ),
    Product: obx_int.EntityDefinition<Product>(
      model: _entities[2],
      toOneRelations: (Product object) => [],
      toManyRelations: (Product object) => {},
      getId: (Product object) => object.id,
      setId: (Product object, int id) {
        object.id = id;
      },
      objectToFB: (Product object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addFloat64(2, object.price);
        fbb.addInt64(3, object.stock);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final priceParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final stockParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final object = Product(
          id: idParam,
          name: nameParam,
          price: priceParam,
          stock: stockParam,
        );

        return object;
      },
    ),
    ShopOrder: obx_int.EntityDefinition<ShopOrder>(
      model: _entities[3],
      toOneRelations: (ShopOrder object) => [],
      toManyRelations:
          (ShopOrder object) => {
            obx_int.RelInfo<CartItem>.toOneBacklink(
                  7,
                  object.id,
                  (CartItem srcObject) => srcObject.shopOrder,
                ):
                object.items,
          },
      getId: (ShopOrder object) => object.id,
      setId: (ShopOrder object, int id) {
        object.id = id;
      },
      objectToFB: (ShopOrder object, fb.Builder fbb) {
        final dateOffset = fbb.writeString(object.date);
        fbb.startTable(4);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, dateOffset);
        fbb.addFloat64(2, object.total);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final dateParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final totalParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final object = ShopOrder(date: dateParam, total: totalParam)
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
        obx_int.InternalToManyAccess.setRelInfo<ShopOrder>(
          object.items,
          store,
          obx_int.RelInfo<CartItem>.toOneBacklink(
            7,
            object.id,
            (CartItem srcObject) => srcObject.shopOrder,
          ),
        );
        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [CartItem] entity fields to define ObjectBox queries.
class CartItem_ {
  /// See [CartItem.id].
  static final id = obx.QueryIntegerProperty<CartItem>(
    _entities[0].properties[0],
  );

  /// See [CartItem.productId].
  static final productId = obx.QueryIntegerProperty<CartItem>(
    _entities[0].properties[1],
  );

  /// See [CartItem.productName].
  static final productName = obx.QueryStringProperty<CartItem>(
    _entities[0].properties[2],
  );

  /// See [CartItem.productPrice].
  static final productPrice = obx.QueryDoubleProperty<CartItem>(
    _entities[0].properties[3],
  );

  /// See [CartItem.productStock].
  static final productStock = obx.QueryIntegerProperty<CartItem>(
    _entities[0].properties[4],
  );

  /// See [CartItem.productQty].
  static final productQty = obx.QueryIntegerProperty<CartItem>(
    _entities[0].properties[5],
  );

  /// See [CartItem.shopOrder].
  static final shopOrder = obx.QueryRelationToOne<CartItem, ShopOrder>(
    _entities[0].properties[6],
  );
}

/// [Customer] entity fields to define ObjectBox queries.
class Customer_ {
  /// See [Customer.id].
  static final id = obx.QueryIntegerProperty<Customer>(
    _entities[1].properties[0],
  );

  /// See [Customer.email].
  static final email = obx.QueryStringProperty<Customer>(
    _entities[1].properties[1],
  );
}

/// [Product] entity fields to define ObjectBox queries.
class Product_ {
  /// See [Product.id].
  static final id = obx.QueryIntegerProperty<Product>(
    _entities[2].properties[0],
  );

  /// See [Product.name].
  static final name = obx.QueryStringProperty<Product>(
    _entities[2].properties[1],
  );

  /// See [Product.price].
  static final price = obx.QueryDoubleProperty<Product>(
    _entities[2].properties[2],
  );

  /// See [Product.stock].
  static final stock = obx.QueryIntegerProperty<Product>(
    _entities[2].properties[3],
  );
}

/// [ShopOrder] entity fields to define ObjectBox queries.
class ShopOrder_ {
  /// See [ShopOrder.id].
  static final id = obx.QueryIntegerProperty<ShopOrder>(
    _entities[3].properties[0],
  );

  /// See [ShopOrder.date].
  static final date = obx.QueryStringProperty<ShopOrder>(
    _entities[3].properties[1],
  );

  /// See [ShopOrder.total].
  static final total = obx.QueryDoubleProperty<ShopOrder>(
    _entities[3].properties[2],
  );

  /// see [ShopOrder.items]
  static final items = obx.QueryBacklinkToMany<CartItem, ShopOrder>(
    CartItem_.shopOrder,
  );
}
